markdown: kramdown
theme: jekyll-theme-minimal
logo: /imgs/logo.gif
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
header: 
  image: "/imgs/header.jpg"
toc: true
sidebar:
  - title: "Title"
    image:  "/imgs/header.jpg" 
    image_alt: "image"
    text: "Some text here."
  - title: "Another Title"
    text: "More text here."
